# https://github.com/actions/deploy-pages#usage
name: Deploy Nuxt site to GitHub Pages
on:
  schedule: # JST 4:00（UTC 19:00）
    - cron: "0 19 */3 * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  # ビルドを実行
  build:
    runs-on: ubuntu-latest
    env:
      NUXT_YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - run: npm install
      - run: npx nuxt build --preset github_pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./.output/public
  # Pagesにデプロイ
  deploy:
    # ビルドジョブに依存関係を追加
    needs: build
    # Pagesデプロイに必要な権限をGITHUB_TOKENに付与
    permissions:
      pages: write # Pagesにデプロイするため
      id-token: write # デプロイが適切なソースから行われていることを検証するため
    # github_pages環境にデプロイ
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # ランナーとデプロイ手順を指定
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
